# Default values for crashing-app
replicaCount: 2

image:
  repository: crashing-app
  tag: "1.1"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080

config:
  appMode: "Debug"

secret:
  apiKey: "MTIzNDUtc2VjcmV0"
