apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashing-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crashing-app
  template:
    metadata:
      labels:
        app: crashing-app
    spec:
      containers:
        - name: app
          image: crashing-app:1.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: crashing-app-config
            - secretRef:
                name: crashing-app-secret
